### PR TITLE
BUG - NJWE-1781 

### PR DESCRIPTION
**Pull request by scwambach**
Resolves - [NJWE-1781](https://fearless.jira.com/browse/NJWE-1781)

## What I did:

- added a regex to extract the search params
-  [x] Design review
-  [ ] Dev Review

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
The issue with the search is working great but the query url does not update when the filters are updated. [Screen recording included](https://www.loom.com/share/9abbf9dc706e408ca01ff6d571343ae4?sid=4dddd3bf-1144-4ab4-a7f9-8b34930662d0):

**Comment by ChelseaKR** [comment]
@scwambach heads up you're getting some failing tests here

**Comment by scwambach** [comment]
> The issue with the search is working great but the query url does not update when the filters are updated. [Screen recording included](https://www.loom.com/share/9abbf9dc706e408ca01ff6d571343ae4?sid=4dddd3bf-1144-4ab4-a7f9-8b34930662d0):

@mflymfly That's never been a feature on the results page, I think that would need at least it's own ticket to accomplish that and a quick discussion.

**Review by mflymfly — APPROVED** [review]
LGTM, will create follow up ticket for the filter query parameter update

**Review by denish-fearless — APPROVED** [review]
LGTM 👍

**Pull request merged**
