### PR TITLE
NJWE-1801 - Update params in url

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-1801](https://fearless.jira.com/browse/NJWE-1801)

## What I did:
- when typing new values into the search filter, it updates in the URL address bar
- now when reloading the page the filters stay the same
- users can more easily share the URL or bookmark where they were
- [ ] Dev review
- [x] Design review

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
Looking good but found a couple thing in the url. Screen recoridng linked.
https://www.loom.com/share/f10314b120da436cba47ad9f8cb3b9b3?sid=768f4205-a9cc-4958-9539-cd84c42ba3bc

- Auto includes 10 miles in url when entering search from adavanced page
- There was also an issue with the url not updating when filters were cleared

Also curious if we want url parameters for anything else like county, CIP, or SOC for example. Could be follow up work.

**Review by mflymfly — APPROVED** [review]
LGTM!

**Review by ChelseaKR — CHANGES_REQUESTED** [review]
Hey Scott! Looks like you're on the right track here. We'd like to do this for all the filters if you can. Some issues I found:

* When I enter a value Zip code and clear it, query parameters aren’t removed
* “Show In-Demand Trainings Only” filter doesn’t add query parameter
* When I enter a value for max cost and clear it, value is removed from URL but query parameter isn’t removed
* “Time to Complete” filter doesn’t add query parameter
* “Provider Services” filter doesn’t add query parameter
* “Languages” filter doesn’t add query parameter
* “Filter by CIP Code” filter doesn’t add query parameter
“Filter by SOC Code” filter doesn’t add query parameter

**Comment by mflymfly** [comment]
Thinking on this, and should the url only update once you click "Update Results"? @ChelseaKR

**Comment by ChelseaKR** [comment]
@mflymfly The results update when the user changes their focus away from the filters. I'd want the URL to update when the results do for the sake of consistency - we could also require users to press the button. WDYT?

**Comment by mflymfly** [comment]
> @mflymfly The results update when the user changes their focus away from the filters. I'd want the URL to update when the results do for the sake of consistency - we could also require users to press the button. WDYT?

@ChelseaKR - I think it is ok for them to update right away but then in that case I don't think we would need the update results button. Agree that the URL should update when the results do though which I think is what is happening now. I think this may have some implications on mobile. I personally would like to move the filters into a popover tray that opens from the bottom.

**Review by ChelseaKR — CHANGES_REQUESTED** [review]
Still seeing the following issues:

* When I enter a value Zip code and clear it, query parameters aren’t removed
* When I enter a value for max cost and clear it, value is removed from URL but query parameter isn’t removed

Let me know if you want help with either of these

**Comment by mflymfly** [comment]
@ChelseaKR @scwambach - should we huddle on this later to get this resolved? I am not seeing the same behavior as you Chelsea (or maybe I am just interpreting it differently) and just want to make sure we are all on the same page.

**Comment by ChelseaKR** [comment]
@scwambach this seems to no longer be loading results at all now

**Pull request merged**
