### PR TITLE
[NJWE-1778] updated for handling no data / 0 occupations

### PR DESCRIPTION
**Pull request by ChelseaKR**
Implements [NJWE-1778](https://fearless.jira.com/browse/NJWE-1778?atlOrigin=eyJpIjoiNmRiNzdkMjY4YTkwNGJlZTkxN2FlZWRkNzk2MTJmYzQiLCJwIjoiaiJ9)

Tasks
* [x] Dev review
* [x] Design review

### CODE REVIEW

**Review by mflymfly — APPROVED** [review]
LGTM

**Review by denish-fearless — CHANGES_REQUESTED** [review]
A little behavior change needs to be addressed in this PR with how we route users when there are no or 0 occupation in my career nj.

Example: Audio and Video Technicians (27-4011)
SOC code has jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=27-4011&location=New%20Jersey&radius=10&source=NLX&currentpage=1)
Example: Layout Workers, Metal and Plastic (51-4192)
SOC code has no jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=&location=New%20Jersey&radius=25&source=NLX&currentpage=1)

**Comment by ChelseaKR** [comment]
> A little behavior change needs to be addressed in this PR with how we route users when there are no or 0 occupation in my career nj.
> 
> Example: Audio and Video Technicians (27-4011) SOC code has jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=27-4011&location=New%20Jersey&radius=10&source=NLX&currentpage=1) Example: Layout Workers, Metal and Plastic (51-4192) SOC code has no jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=&location=New%20Jersey&radius=25&source=NLX&currentpage=1)

@denish-fearless @mflymfly just confirming here - so when an occupation has 0 jobs available, the link should go to the search for ALL jobs in NJ?

**Comment by denish-fearless** [comment]
> > A little behavior change needs to be addressed in this PR with how we route users when there are no or 0 occupation in my career nj.
> > Example: Audio and Video Technicians (27-4011) SOC code has jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=27-4011&location=New%20Jersey&radius=10&source=NLX&currentpage=1) Example: Layout Workers, Metal and Plastic (51-4192) SOC code has no jobs > link goes to [link](https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=&location=New%20Jersey&radius=25&source=NLX&currentpage=1)
> 
> @denish-fearless @mflymfly just confirming here - so when an occupation has 0 jobs available, the link should go to the search for ALL jobs in NJ?

That sounds about right after having conversation with @mflymfly

**Review by denish-fearless — APPROVED** [review]
LGTM 👍

**Pull request merged**
